version: '{build}'
image:
- Visual Studio 2019
- Ubuntu
environment:
  NUGETAPIKEY:
    secure: /FLJCPNtLDyXDbw62wnY4tBc3kRJMPNbttutkzVhCdUDEmg9pjEBGZnBVpBTemKK
  BUILD_BOT_PASSWORD:
    secure: wJ9JVS5hSAp9ItYlHKxTPg==
  APPVEYOR_YML_DISABLE_PS_LINUX: true
build_script:
- ps: .\build.ps1 --target=NuGetPublish """--trigger=$env:APPVEYOR_REPO_TAG_NAME""" "--nugetApiKey=$env:NUGETAPIKEY"
- sh: ./build.sh --target=NuGetPackageTest
test: off
artifacts:
- path: 'release\*.nupkg'
